package ch.study.urlshortener.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter // Setters are used in aws-java-dynamodb-sdk
@NoArgsConstructor
@DynamoDBTable(tableName = "Url")
public class Url {

  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  private String id;

  @DynamoDBAttribute
  @DynamoDBIndexHashKey(globalSecondaryIndexName = "shortenUrl")
  private String shortenUrl;

  @DynamoDBAttribute
  private String originUrl;

  @Builder
  public Url(String shortenUrl, String originUrl) {
    this.shortenUrl = shortenUrl;
    this.originUrl = originUrl;
  }
}
